global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'baselinker-integration'

scrape_configs:
  - job_name: 'baselinker-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx:80']
        labels:
          service: 'baselinker-integration'
          environment: 'development'

